name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: |
        mkdir -p ~/.config/nix
        echo system-features = kvm nixos-test >> ~/.config/nix/nix.conf

        git apply < ./make-small.patch
        ./scripts/paths.sh
        # Fetch dependencies
        xargs <fetched nix-store --realise

        # Build things to build
        nix-build tests -k

  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install fd
      run: |
        sudo apt-get install fd-find
    - name: Check scripts with shellcheck
      run: |
        fdfind .sh$ . \
          --exclude home-manager \
          --exec shellcheck
