name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build dependencies
      run: |
        git apply < ./make-small.patch

        # build deps
        drvs=$(nix-instantiate tests)
        deps=$(nix-store --query --references --include-outputs $drvs)
        nix-store --realise $deps

    # Run tests one by one
    - run: nix-build tests -A vim-hls-error
      if: success() || failure()
    - run: nix-build tests -A vim-complete-docs
      if: success() || failure()
    - run: nix-build tests -A vim-diagnostic-list
      if: success() || failure()

    # Run any leftover tests
    - run: nix-build tests

  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install fd
      run: |
        sudo apt-get install fd-find
    - name: Check scripts with shellcheck
      run: |
        fdfind .sh$ . \
          --exclude home-manager \
          --exec shellcheck
